### ISSUE TITLE
EXC_BAD_ACCESS while trying to run basic-move example

### ISSUE THREAD

**Issue by harpreets** [CreativeInquiry/ofxRobotArm#2]
I just gave a shot to the ofxRobotArm and get an error while trying to the run the **_example-basic-move_**. The error seemingly occurs after the 10th time drawGUI() is run from ofApp.cpp and XCode then terminates at the ofTesselator::performTessellation function. Screenshot below:

![image](https://cloud.githubusercontent.com/assets/1071915/16515280/100be0a8-3fac-11e6-9c5b-a99f2e6f077c.png)

Any ideas on what could possibly be wrong here? The application does run for some frames (screenshot below) - I don't see the virtual robot models though - and then it crashes at the above line.

![image](https://cloud.githubusercontent.com/assets/1071915/16515611/ef3a8044-3fad-11e6-8290-627c5fbcee1b.png)

**Current environment**: Max OSX 10.11 (64-bit El Capitan), XCode 7.3, oF 0.9.3, Robot Arm - UR3 (connected to computer via Ethernet to USB converter)
Addons/Dependencies were all installed by terminal run of _installAddons.sh_

**Comment by danzeeeman** [comment]
This might be a ofxGUI issue. Can you try running in Release?

**Comment by harpreets** [comment]
Release does work indeed.
