### ISSUE TITLE
Recommended MoCap/Mocappath example settings?

### ISSUE THREAD

**Issue by harpreets** [CreativeInquiry/ofxRobotArm#4]
**My Windows setup**: Optitrack 6-camera, Motive (1.9.0) on a Windows (8.1) machine [Firewall access on network allowed], Broadcasting on Wireless LAN through Motive
**My MAC Setup**: _example-follow-mocap_ running through Xcode (to use ofxNatNet parsing already existing in the example), Wired LAN connection for UR3

However, it seems like like I'm not getting any rigidbody data on my Mac application even when I tried to use the simple _ofxNatNet_ example. The same example on Windows machine with Motive set on _loopback_ and server/localinterface set as _127.0.0.1_ in ofxNatNet example works perfectly fine for streaming. (I am also then able to transmit this rigidbody data through OSC over Wifi just to check if my wireless connection is fine)

For streaming from Windows (Motive) to Mac (ofxNatNet) - Server IP is confirmed set as the Wireless LAN IP of Windows machine and local interface is set as Wireless LAN IP for Mac. However, I am not getting the connection established or any rigid body data currently. Any recommended settings for establishing the connection or something that might be missing?

**Comment by madelinegannon** [comment]
Here's a screenshot of our Data Streaming setup for Motive Tracker 1.9.0:
![streaming-settings-motive-tracker-1_9_0](https://cloud.githubusercontent.com/assets/3160264/16592260/df723c6c-42ad-11e6-9726-642355565b04.png)

You can also try rearranging your LAN connection in System Preferences > Network on your mac. Arrange the LAN connection above your wifi connection.

**Comment by harpreets** [comment]
Well, things are a bit mysterious here.

I have the same settings in Motive (1.9.0) and my network analyzer (Wireshark) shows quite some data being sent every ms. I did a screen cap and pushed it here: [https://youtu.be/txat5g87qy8](url) - which shows that the data is being sent indeed.

However, on the Mac side where bare ofxNatNet example is running - I am getting an erratic behavior. The connection goes on/off and I do not receive any rigidbody data at all. Screencap for this is here: https://youtu.be/7tfKDfM05VA

In addition, what's not working:
- Tried to downgrade to Motive 1.8.0 to see if data streaming works better but that version has bugs with camera calibration which prevents me setting up the environment.
- Tried to upgrade to Motive 1.10.0 but ofxNatNet gives an error saying the NatNet parsing for this version is old
- Tried to bring the whole example-mocap to Windows so that I run everything from one machine but seems mocap or other files have some dependencies which doesn't allow a Windows build

When I do run the ofxNatNet client on the same Windows machine as the Motive and server IP/local interface as 192.168.11.5 (same as the local interface in Motive) - I do get the rigidbody data, right frame speed etc.

**Comment by harpreets** [comment]
Currently only on one Wireless network.

**Comment by danzeeeman** [comment]
Oh you should not use WIFI that causes major issues. We setup a wired lan
here at the studio

**Comment by harpreets** [comment]
^ This seems to have solved it for me.

**Comment by danzeeeman** [comment]
I'll make a note in our docs about needing a LAN vs WiFi

Thanks!
