### ISSUE TITLE
some examples are not working : libc++abi.dylib terminating with uncaught exception of type std::out_of_range: basic_string

### ISSUE THREAD

**Issue by nahbee10** [CreativeInquiry/ofxRobotArm#6]
I'm working on UR5. Before i connect the machine with the OF app i tried opening ofxRobotArm example projects offline as just a simulation.

But whenever i tried to open **'example-follow-path' / 'example-follow-surface'** using OF, i couldn't open them and saw this error message

<img width="1184" alt="screen shot 2016-07-18 at 11 57 02 am" src="https://cloud.githubusercontent.com/assets/12539032/16921766/daec6162-4ce0-11e6-9834-3d1fc5052d17.png">

## libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string

I installed all the dependent addons and i also built the projects as release mode.

I found only this openframeworks thread about ofxRobotArm.

https://forum.openframeworks.cc/t/ofxrobotarm-usage/23819/6

This case was different from mine. I can't even open the window after finishing building the projects. But the guy can open it so that he could access the 'set TCP' toggle. 

Any helps will be appreciated.

**Comment by danzeeeman** [comment]
Please add what versions of the Addons you are running, OSX version, and OF
version you are building against.

In each Addon to do this:

git branch -v
git log

And add the branch name and the commit ID for each of your Addons

**Comment by nahbee10** [comment]
POET🐚  ⥤  cd ofxGML
POET🐚  ⥤  git branch -v
* master 6b0b261 Add files via upload
POET🐚  ⥤  git log
commit 6b0b261e203f3c1e844b17a678f9a131e3f2cfa5
commit 6b0b261e203f3c1e844b17a678f9a131e3f2cfa5
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Tue May 10 15:57:28 2016 -0400

    Add files via upload

commit 9fed1d71e168dd5054bb4909f6ef82e7652bf481
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Tue May 10 15:41:10 2016 -0400

    Add files via upload

commit ba27c562df4d95ea94e07678319c06627803bd10
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Sun Apr 17 15:07:39 2016 -0400

    old code is old

commit 7a11cd120f0efe6857ba8e90a391a6bf2acaafb4
Merge: f20b7ef 01caae7
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Thu Apr 7 11:52:04 2016 -0400

    Merge branch 'master' of https://github.com/danzeeeman/ofxGML


POET🐚  ⥤  cd ofxGizmo
POET🐚  ⥤  git branch -v
* master cae7ff8 updates to 0.9.0+
POET🐚  ⥤  git log
commit cae7ff87dde7ebe4768f0546610de01b2513816c
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Mon May 2 17:21:49 2016 -0400

    updates to 0.9.0+

commit fff5ef017c823496a93c214d2cd9c815a377db46
Author: NickHardeman <nickhardeman@gmail.com>
Date:   Wed Dec 9 22:50:31 2015 -0500

    fix for head size

commit 5d14bf094c6220280e8460711218c19fd8059815
Author: NickHardeman <nickhardeman@gmail.com>
Date:   Wed Dec 9 22:50:15 2015 -0500

    update for 009

commit 87673986e781a36d174b5b7028fef1685e03368e
Author: NickHardeman <nickhardeman@gmail.com>
Date:   Wed Dec 9 22:45:09 2015 -0500

    maintain arrow head size regardless of camera location

POET🐚  ⥤  cd ofxNatNet
POET🐚  ⥤  git branch -v
* master 90457cb tweaks to work on the STUDIO's Optitrack
POET🐚  ⥤  git log
commit 90457cb3d43aa2361e50eb2bc99c9946526f6708
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Tue Mar 22 12:48:14 2016 -0400

    tweaks to work on the STUDIO's Optitrack

commit b0f6862c8dd7d22acb38bab560bf2686b6e35163
Author: Satoru Higa <satoruhiga@gmail.com>
Date:   Tue Feb 16 06:01:18 2016 +0900

    Add ofxNatNetLib for ofxAddonLib

commit e8874cbd1667536b101f8533a46bb489ca958168
Author: Satoru Higa <satoruhiga@gmail.com>
Date:   Tue Jan 26 18:37:52 2016 +0900

    Fix network interface name problem

commit d3b117725479e1c88d7f7439193a6c69fd91233d
Author: Satoru Higa <satoruhiga@gmail.com>
Date:   Mon Jan 25 23:09:21 2016 +0900

    Update to natnet v2.9


POET🐚  ⥤  cd ofxTimeline
POET🐚  ⥤  git branch -v
* master 015b6db updates to 0.9.0 and fixes
POET🐚  ⥤  git log
commit 015b6db278b0b8b12362602949bf34919da38f8a
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Mon May 2 17:24:17 2016 -0400

    updates to 0.9.0 and fixes

commit 0ad5b9ee92defa6f3f397f592128ade6840867ac
Merge: 81d2179 a897ac9
Author: James George <james@jamesgeorge.org>
Date:   Fri Apr 1 20:04:23 2016 -0700

    Merge pull request #130 from emmanuelgeoffray/feature-fix-video-play-pause-linux

    Feature fix video play pause linux

commit 81d2179066c815543f9fff3747e8023fc239c612
Merge: 6c51505 ab24ee6
Author: James George <james@jamesgeorge.org>
Date:   Fri Apr 1 20:04:09 2016 -0700

    Merge pull request #129 from prisonerjohn/master

    0.9.0 Update


POET🐚  ⥤  cd ofxURDriver
POET🐚  ⥤  git branch -v
* master 1341f92 fixing bugs
POET🐚  ⥤  git log
commit 1341f9276e7ba5fb76493669d7903c6352364071
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Wed Jun 22 14:25:59 2016 -0400

    fixing bugs

commit 384a2bf2ff78d185ba7e72601a54b622ae4836fa
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Wed Jun 22 14:15:27 2016 -0400

    remove physics

commit 79fb90708982d11411faf4c90a54268367359b49
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Wed Jun 22 14:12:49 2016 -0400

    fixes

commit ae74cc47579bf0e5b937a191e84e24f1e145076d
Merge: 8f8bc46 e5997b9
Author: Dan Moore <dan@makeitdoathing.com>
Date:   Wed Jun 22 14:09:36 2016 -0400

    Merge branch 'master' of https://github.com/danzeeeman/ofxURDriver


POET🐚  ⥤  cd ofxTiming
POET🐚  ⥤  git branch -v
* master 888c4c4 Merge pull request #2 from mgsx-dev/fix/addon-example
POET🐚  ⥤  git log
commit 888c4c40d8c3986574a6ee48aa7da66aec6f2a25
Merge: deb465d 5dbae9b
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Wed Jan 20 12:30:18 2016 +0100

    Merge pull request #2 from mgsx-dev/fix/addon-example

    add missing dependency to example project

commit 5dbae9bdcf0da8bc99722712cca4ce7cd0615ad4
Author: Germain AUBERT <germain.aubert@gmail.com>
Date:   Wed Jan 20 12:13:50 2016 +0100

    add missing dependency to example project

commit deb465dc7694f6bdd12dd45e34b472cca5bb71a3
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Jul 25 12:34:19 2015 -0400

    added example, closes #1, changed wasTriggered and wasUntriggered to const, reset on update

commit cba2bc558e470ad8a896629651f2152a761e649c
Author: Kyle McDonald <kyle@kylemcdonald.net>


POET🐚  ⥤  cd ofxPtf
POET🐚  ⥤  git branch -v
* master bce0f2b updated matrix stack calls to use of rather than gl versions to work with programmable renderer
POET🐚  ⥤  git log
commit bce0f2b23130d39c46cf1c4d9839415484e5b6d1
Author: Neil Mendoza <neil@isthis.gd>
Date:   Thu Apr 16 15:56:12 2015 -0700

    updated matrix stack calls to use of rather than gl versions to work with programmable renderer

commit 1c1e3d5f0ffd5e0acd2d93d94a6b04a38e4be679
Author: Neil Mendoza <neil@isthis.gd>
Date:   Sat Nov 16 14:32:47 2013 +0000

    tweaks

commit e5ec3a3102c67fbe03b7af3c49703ad010f136d9
Author: Neil Mendoza <neil@isthis.gd>
Date:   Fri Oct 18 11:24:09 2013 +0100

    added clear()

commit e0ee8fe36ce532358c02c6aee17161b0e8ae54de
Author: Neil Mendoza <neil@isthis.gd>
Date:   Sat Feb 23 19:02:56 2013 +0000

    Fixed comment

commit bf849a2c9f9f7723bd82eeaba86dff9a3110c706
Author: Neil Mendoza <neil@isthis.gd>
Date:   Sat Feb 23 19:02:31 2013 +0000

    Fixed comment

commit bc70771842e2d1670851313b75f4273dc2eb492a
Author: Neil Mendoza <neil@isthis.gd>
Date:   Sat Feb 23 12:14:23 2013 +0000

    Update readme.md


POET🐚  ⥤  cd ofxCv
POET🐚  ⥤  git branch -v
* master 85f8a34 Merge pull request #190 from companje/patch-1
POET🐚  ⥤  git log
commit 85f8a34a2ed07db44d4b97c14c8f5019f3bcfb71
Merge: 0e5eb4f 1e6c909
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sun May 1 22:54:45 2016 -0400

    Merge pull request #190 from companje/patch-1

    fixes that the number of points in getCurrent and getMotion were not equal

commit 1e6c909ab076d41c2cb47184836788a010c628a3
Author: Rick Companje <rick@companje.nl>
Date:   Sun May 1 22:25:40 2016 +0200

    fixes that the number of points in getCurrent and getMotion were not equal

commit 0e5eb4fdc9c209109ba8cf9cb5c2d9ca9c7ac4ba
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Fri Apr 15 17:07:41 2016 -0400

    added holes to ContourFinder, closes #21

commit 70abc5fdc6f66f7a3cbd451ebf4b86abc6f452ad
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 01:53:51 2016 -0500
:...skipping...
commit 85f8a34a2ed07db44d4b97c14c8f5019f3bcfb71
Merge: 0e5eb4f 1e6c909
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sun May 1 22:54:45 2016 -0400

    Merge pull request #190 from companje/patch-1

    fixes that the number of points in getCurrent and getMotion were not equal

commit 1e6c909ab076d41c2cb47184836788a010c628a3
Author: Rick Companje <rick@companje.nl>
Date:   Sun May 1 22:25:40 2016 +0200

    fixes that the number of points in getCurrent and getMotion were not equal

commit 0e5eb4fdc9c209109ba8cf9cb5c2d9ca9c7ac4ba
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Fri Apr 15 17:07:41 2016 -0400

    added holes to ContourFinder, closes #21

commit 70abc5fdc6f66f7a3cbd451ebf4b86abc6f452ad
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 01:53:51 2016 -0500

:...skipping...
commit 85f8a34a2ed07db44d4b97c14c8f5019f3bcfb71
Merge: 0e5eb4f 1e6c909
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sun May 1 22:54:45 2016 -0400

    Merge pull request #190 from companje/patch-1

    fixes that the number of points in getCurrent and getMotion were not equal

commit 1e6c909ab076d41c2cb47184836788a010c628a3
Author: Rick Companje <rick@companje.nl>
Date:   Sun May 1 22:25:40 2016 +0200

    fixes that the number of points in getCurrent and getMotion were not equal

commit 0e5eb4fdc9c209109ba8cf9cb5c2d9ca9c7ac4ba
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Fri Apr 15 17:07:41 2016 -0400

    added holes to ContourFinder, closes #21

commit 70abc5fdc6f66f7a3cbd451ebf4b86abc6f452ad
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 01:53:51 2016 -0500

    everything looks good
:...skipping...
commit 85f8a34a2ed07db44d4b97c14c8f5019f3bcfb71
Merge: 0e5eb4f 1e6c909
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sun May 1 22:54:45 2016 -0400

    Merge pull request #190 from companje/patch-1

    fixes that the number of points in getCurrent and getMotion were not equal

commit 1e6c909ab076d41c2cb47184836788a010c628a3
Author: Rick Companje <rick@companje.nl>
Date:   Sun May 1 22:25:40 2016 +0200

    fixes that the number of points in getCurrent and getMotion were not equal

commit 0e5eb4fdc9c209109ba8cf9cb5c2d9ca9c7ac4ba
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Fri Apr 15 17:07:41 2016 -0400

    added holes to ContourFinder, closes #21

commit 70abc5fdc6f66f7a3cbd451ebf4b86abc6f452ad
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 01:53:51 2016 -0500

    everything looks good

commit 4cfedb7898ef9334b0bb7ea5fec445bc6c1e4959
:...skipping...
commit 85f8a34a2ed07db44d4b97c14c8f5019f3bcfb71
Merge: 0e5eb4f 1e6c909
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sun May 1 22:54:45 2016 -0400

    Merge pull request #190 from companje/patch-1

    fixes that the number of points in getCurrent and getMotion were not equal

commit 1e6c909ab076d41c2cb47184836788a010c628a3
Author: Rick Companje <rick@companje.nl>
Date:   Sun May 1 22:25:40 2016 +0200

    fixes that the number of points in getCurrent and getMotion were not equal

commit 0e5eb4fdc9c209109ba8cf9cb5c2d9ca9c7ac4ba
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Fri Apr 15 17:07:41 2016 -0400

    added holes to ContourFinder, closes #21

commit 70abc5fdc6f66f7a3cbd451ebf4b86abc6f452ad
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 01:53:51 2016 -0500

    everything looks good

commit 4cfedb7898ef9334b0bb7ea5fec445bc6c1e4959
Author: Kyle McDonald <kyle@kylemcdonald.net>
:...skipping...
commit 85f8a34a2ed07db44d4b97c14c8f5019f3bcfb71
Merge: 0e5eb4f 1e6c909
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sun May 1 22:54:45 2016 -0400

    Merge pull request #190 from companje/patch-1

    fixes that the number of points in getCurrent and getMotion were not equal

commit 1e6c909ab076d41c2cb47184836788a010c628a3
Author: Rick Companje <rick@companje.nl>
Date:   Sun May 1 22:25:40 2016 +0200

    fixes that the number of points in getCurrent and getMotion were not equal

commit 0e5eb4fdc9c209109ba8cf9cb5c2d9ca9c7ac4ba
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Fri Apr 15 17:07:41 2016 -0400

    added holes to ContourFinder, closes #21

commit 70abc5fdc6f66f7a3cbd451ebf4b86abc6f452ad
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 01:53:51 2016 -0500

    everything looks good

commit 4cfedb7898ef9334b0bb7ea5fec445bc6c1e4959
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 00:58:55 2016 -0500
:...skipping...
commit 85f8a34a2ed07db44d4b97c14c8f5019f3bcfb71
Merge: 0e5eb4f 1e6c909
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sun May 1 22:54:45 2016 -0400

    Merge pull request #190 from companje/patch-1

    fixes that the number of points in getCurrent and getMotion were not equal

commit 1e6c909ab076d41c2cb47184836788a010c628a3
Author: Rick Companje <rick@companje.nl>
Date:   Sun May 1 22:25:40 2016 +0200

    fixes that the number of points in getCurrent and getMotion were not equal

commit 0e5eb4fdc9c209109ba8cf9cb5c2d9ca9c7ac4ba
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Fri Apr 15 17:07:41 2016 -0400

    added holes to ContourFinder, closes #21

commit 70abc5fdc6f66f7a3cbd451ebf4b86abc6f452ad
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 01:53:51 2016 -0500

    everything looks good

commit 4cfedb7898ef9334b0bb7ea5fec445bc6c1e4959
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 00:58:55 2016 -0500

:...skipping...
commit 85f8a34a2ed07db44d4b97c14c8f5019f3bcfb71
Merge: 0e5eb4f 1e6c909
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sun May 1 22:54:45 2016 -0400

    Merge pull request #190 from companje/patch-1

    fixes that the number of points in getCurrent and getMotion were not equal

commit 1e6c909ab076d41c2cb47184836788a010c628a3
Author: Rick Companje <rick@companje.nl>
Date:   Sun May 1 22:25:40 2016 +0200

    fixes that the number of points in getCurrent and getMotion were not equal

commit 0e5eb4fdc9c209109ba8cf9cb5c2d9ca9c7ac4ba
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Fri Apr 15 17:07:41 2016 -0400

    added holes to ContourFinder, closes #21

commit 70abc5fdc6f66f7a3cbd451ebf4b86abc6f452ad
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 01:53:51 2016 -0500

    everything looks good

commit 4cfedb7898ef9334b0bb7ea5fec445bc6c1e4959
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 00:58:55 2016 -0500

    updated video file, updated examples for gui
:...skipping...
commit 85f8a34a2ed07db44d4b97c14c8f5019f3bcfb71
Merge: 0e5eb4f 1e6c909
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sun May 1 22:54:45 2016 -0400

    Merge pull request #190 from companje/patch-1

    fixes that the number of points in getCurrent and getMotion were not equal

commit 1e6c909ab076d41c2cb47184836788a010c628a3
Author: Rick Companje <rick@companje.nl>
Date:   Sun May 1 22:25:40 2016 +0200

    fixes that the number of points in getCurrent and getMotion were not equal

commit 0e5eb4fdc9c209109ba8cf9cb5c2d9ca9c7ac4ba
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Fri Apr 15 17:07:41 2016 -0400

    added holes to ContourFinder, closes #21

commit 70abc5fdc6f66f7a3cbd451ebf4b86abc6f452ad
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 01:53:51 2016 -0500

    everything looks good

commit 4cfedb7898ef9334b0bb7ea5fec445bc6c1e4959
Author: Kyle McDonald <kyle@kylemcdonald.net>
Date:   Sat Mar 5 00:58:55 2016 -0500

    updated video file, updated examples for gui

:


--------------------------- 
here!

**Comment by danzeeeman** [comment]
Hey I just need the first commit id not the whole log.

**Comment by danzeeeman** [comment]
Did you install all of ofxTimeline and its dependancies?

**Comment by danzeeeman** [comment]
You might need to regenerate the project files with the project generator

**Comment by danzeeeman** [comment]
@nahbee10 can you please correct the post with the addons and commit ids to be like this:

ADDON_NAME |  BRANCH_NAME | LAST COMMIT ID

example:

ofxGML | master | 6b0b261e203f3c1e844b17a678f9a131e3f2cfa5

I also just completed a fresh setup in a new OF folder and cannot reproduce your issue.  I downloaded 0.9.3 from openFrameworks.cc.  Cloned ofxRobotArm. Ran the installAddons.sh script from ofxRobotArm.  Ran the clone_Addons.sh from ofxTimeline.  Opened the example-basic-move and was able to build and run it on my machine without any issues.

**Comment by danzeeeman** [comment]
@nahbee10 are you able to build any example?  I'm not following the issue completely?

**Comment by nahbee10** [comment]
@danzeeeman yeah i can build&launch example-basic-move 
And i succeeded building example-follow-path and example-follow-surface but can't launch them because of this error
And soon i'll change the post. wait a moment

**Comment by danzeeeman** [comment]
Ok pull ofxRobotArm.
It was some weird bug in the file reader

**Comment by nahbee10** [comment]
yeah now working well!!! Thanks!!!! @danzeeeman
